name: Build macOS app for testing A

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-13,macos-14]
        architecture: [x64]
        python-version: ['3.11','3.13']
        exclude:
          - os: macos-13
            python-version: '3.13'
          - os: macos-14
            python-version: '3.11'

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        ref: 'icons'
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        architecture: ${{ matrix.architecture }}
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pyinstaller setuptools wheel cython cffi -r requirements.txt
    - name: Build Cython ext
      run: |
        python setup.py build_ext --inplace
    - name: Make pyinstaller spec
      run: |
        pyi-makespec --windowed --name "Pronterface" --add-data "printrun/assets:printrun/assets" --icon "./assets_raw/icons/pronterface.icns" pronterface.py
        # Edit spec file
        export GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
        export VERSION="$(python3 -c 'import printrun.printcore as core; print(core.__version__)' 2>/dev/null)"
        export YEAR=$(date +%Y)
        sed -i '' '$ s/.$//' Pronterface.spec
        cat >> Pronterface.spec <<EOL
        info_plist={
            'CFBundleVersion': '$GIT_HASH',
            'CFBundleShortVersionString': "$VERSION",
            'NSHumanReadableCopyright': "FOSS Â© $YEAR, GPL-3.0 licensed",
            'NSPrincipalClass': 'NSApplication',
            'NSAppleScriptEnabled': False,
            'NSAppSleepDisabled': True,
          },
        )
        EOL
    - name: Make pyinstaller build
      run: |
        pyinstaller --clean Pronterface.spec -y
        # Zip app manually to avoid losing execute permissions for binary file in app
        cd dist
        zip -r -X Pronterface-app.zip Pronterface.app

    - name: Copy translation files
      run: |
        cp -r locale dist
        cp README.md dist/

    - name: Configuration for testing
      run: |
        echo "EXE_NAME=${{ github.ref_name }}_macos_${{ matrix.architecture }}" >> $GITHUB_ENV

    - name: Upload artifacts for inspection
      uses: actions/upload-artifact@v5
      with:
        name: ${{ env.EXE_NAME }}
        path: |
            dist/Pronterface-app.zip
            dist/README.md
            dist/locale

